version: '2'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      CERT_NAME: shared
      PMA_HOST: mysql
      PMA_PASSWORD: asklaskl
      PMA_USER: root
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  frontend-proxy:
    image: rancher/lb-service-haproxy:v0.6.2
    ports:
    - 443:443/tcp
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
  mysql:
    image: chameleonsystem/docker-services:mysql-5.7
    environment:
      MYSQL_ROOT_PASSWORD: asklaskl
    stdin_open: true
    volumes:
    - mysql:/var/lib/mysql
    tty: true
    ports:
    - 3306:3306/tcp
    labels:
      io.rancher.container.pull_image: always
