version: '2'
.catalog:
  name: "Chameleon Host Services"
  version: "1.2"
  description: "Rancher HAProxy, PHPMyAdmin and MySQL. Version 1.2 Changelog: Switched from nginx proxy to HAProxy. PLEASE NOTE: YOU HAVE TO HAVE AN SSL CERT CALLED Snakeoil INSTALLED!"
  questions:
    - variable: "phpmyadmin_vhost_name"
      description: "The virtual host name you want phpmyadmin to be accessible at"
      label: "PhpMyAdmin vhost name"
      type: "string"
      required: true
      default: "phpmyadmin.devbox-yourname.intra"
services:
  phpmyadmin:
    scale: 1
    start_on_create: true
  frontend-proxy:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      config: |-
        frontend http-frontend
            bind *:80
            mode http
            redirect scheme https if !{ ssl_fc }
        defaults
            timeout client 10m
            timeout server 10m
            timeout connect 10m
      default_cert: Snakeoil
      port_rules:
      - hostname: ${phpmyadmin_vhost_name}
        priority: 2
        protocol: https
        service: phpmyadmin
        source_port: 443
        target_port: 80
      - hostname: '*'
        path: ''
        priority: 6
        protocol: http
        selector: foo=bar
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
  mysql:
    scale: 1
    start_on_create: true



