version: '2'
.catalog:
  name: "Chameleon Host Services"
  version: "1.3"
  description: "Rancher HAProxy, PHPMyAdmin and MySQL. Version 1.3 Changelog: Switched from nginx proxy to HAProxy"
services:
  phpmyadmin:
    scale: 1
    start_on_create: true
  frontendproxy:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      config: |-
        frontend http-frontend
            bind *:80
            mode http
            redirect scheme https if !{ ssl_fc }
      default_cert: Snakeoil
      port_rules:
      - hostname: ${phpmyadmin_vhost_name}
        priority: 2
        protocol: https
        service: phpmyadmin
        source_port: 443
        target_port: 80
      - hostname: '*'
        path: ''
        priority: 6
        protocol: http
        selector: foo=bar
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
  mysql:
    scale: 1
    start_on_create: true



