.catalog:
  name: "Chameleon 6.1"
  version: "6.1"
  description: "Shop and Content Management"

  questions:
    - variable: "phpversion"
      label: "PHP Version"
      description: "Select the php version you want for this project"
      default: php-7.0-fpm
      required: true
      type: "enum"
      options:
        - php-7.0-fpm
        - php-5.6-fpm
    - variable: "host_project_root"
      description: "Enter the project root on your host system (without trailing /customer)"
      label: "Project root on host"
      type: "string"
      required: true
      default: "/home/wwwusers/yourprojectname"
    - variable: "host_ip"
      description: "Enter the IP of your host machine so xdebug can connect to it"
      label: "Host IP"
      type: "string"
      required: true
      default: "192.168.1.0"
    - variable: "user_id"
      description: "The id your user has on the host machine"
      label: "Your system user ID"
      type: "int"
      required: true
      default: "1000"
    - variable: "user_name"
      description: "The name your user has on the host machine"
      label: "Your system user name"
      type: "string"
      required: true
      default: "developer"
    - variable: "virtual_host"
      description: "The virtual host name you want this project to be accessible at"
      label: "Virtual host name"
      type: "string"
      required: true
      default: "yourprojectname.devbox-yourname.intra"


