.catalog:
  name: "Chameleon Project"
  version: "1.4"
  description: "Default Project Stack for Chameleon"

  questions:
    - variable: "phpversion"
      label: "PHP Version"
      description: "Select the php version you want for this project"
      default: chameleonsystem/docker-services:php-7.1-fpm
      required: true
      type: "enum"
      options:
        - chameleonsystem/docker-services:php-7.1-fpm
        - chameleonsystem/docker-services:php-5.6-fpm
        - docker.esono.de:5000/docker-services-private:php-7.1-fpm-oci
        - docker.esono.de:5000/docker-services-private:php-5.6-fpm-oci
    - variable: "service_mysql"
      description: "Select the mysql service you want to use. Be sure to start host services first!"
      label: "Service link to mysql"
      type: "service"
      required: true
    - variable: "host_project_root"
      description: "Enter the project root on your host system (without trailing /customer)"
      label: "Project root on host"
      type: "string"
      required: true
      default: "/home/wwwusers/yourprojectname"
    - variable: "epp_xdebug"
      description: "Set to true if you want to enable XDEBUG. False is recommended for production"
      label: "Activate XDEBUG"
      type: "string"
      required: true
      type: "enum"
      options:
        - false
        - true
    - variable: "epp_blackfire"
      description: "Set to true if you want to enable Blackfire. False is recommended for production. XDEBUG should be disabled when Blackfire is enabled!"
      label: "Activate Blackfire"
      type: "string"
      required: true
      type: "enum"
      options:
        - false
        - true
    - variable: "blackfire_client_id"
      description: "Enter your personal Blackfire client id"
      label: "Blackfire ClientId"
      type: "string"
      required: true
      default: ""
    - variable: "blackfire_client_token"
      description: "Enter your personal Blackfire client token"
      label: "Blackfire ClientToken"
      type: "string"
      required: true
      default: ""
    - variable: "blackfire_server_id"
      description: "Enter your personal Blackfire server id"
      label: "Blackfire ServerId"
      type: "string"
      required: true
      default: ""
    - variable: "blackfire_server_token"
      description: "Enter your personal Blackfire server token"
      label: "Blackfire ServerToken"
      type: "string"
      required: true
      default: ""
    - variable: "host_ip"
      description: "Enter the IP of your host machine so xdebug can connect to it"
      label: "Host IP"
      type: "string"
      required: true
      default: "192.168.1.0"
    - variable: "user_id"
      description: "The id your user has on the host machine"
      label: "Your system user ID"
      type: "int"
      required: true
      default: "1000"
    - variable: "user_name"
      description: "The name your user has on the host machine"
      label: "Your system user name"
      type: "string"
      required: true
      default: "developer"
    - variable: "epp_show_errors"
      description: "Set to true if you want to see all PHP errors in your browser. False is recommended for production"
      label: "Show PHP errors in browser"
      type: "string"
      required: true
      type: "enum"
      options:
        - false
        - true