nginx:
  ports:
  - 80:80/tcp
  - 443:443/tcp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: chameleonsystem/docker-services:nginx-proxy-latest
  volumes:
  - /var/run/docker.sock:/tmp/docker.sock:ro
  stdin_open: true
mysql:
  ports:
  - 127.0.0.1:3306:3306/tcp
  environment:
    MYSQL_ROOT_PASSWORD: asklaskl
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: chameleonsystem/docker-services:mysql-5.6
  volumes:
  - mysql:/var/lib/mysql
  stdin_open: true
phpmyadmin:
  environment:
    VIRTUAL_HOST: ${phpmyadmin_vhost_name}
    CERT_NAME: shared
    PMA_HOST: mysql
    PMA_USER: root
    PMA_PASSWORD: asklaskl
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: phpmyadmin/phpmyadmin
  stdin_open: true
