.catalog:
  name: "DEPRECATED Chameleon 6.1"
  version: "DEPRECATED 6.1"
  description: "Project stack for Chameleon as of 6.1 including PHP7 support"

  questions:
    - variable: "phpversion"
      label: "PHP Version"
      description: "Select the php version you want for this project"
      default: chameleonsystem/docker-services:php-7.0-fpm
      required: true
      type: "enum"
      options:
        - chameleonsystem/docker-services:php-7.0-fpm
        - chameleonsystem/docker-services:php-5.6-fpm
        - docker.esono.de:5000/docker-services-private:php-7.0-fpm-oci
        - docker.esono.de:5000/docker-services-private:php-5.6-fpm-oci
    - variable: "service_mysql"
      description: "Select the mysql service you want to use. Be sure to start host services first!"
      label: "Service link to mysql"
      type: "service"
      required: true
    - variable: "host_project_root"
      description: "Enter the project root on your host system (without trailing /customer)"
      label: "Project root on host"
      type: "string"
      required: true
      default: "/home/wwwusers/yourprojectname"
    - variable: "epp_xdebug"
      description: "Set to true if you want to enable XDEBUG. False is recommended for production"
      label: "Activate XDEBUG"
      type: "string"
      required: true
      type: "enum"
      options:
        - false
        - true
    - variable: "host_ip"
      description: "Enter the IP of your host machine so xdebug can connect to it"
      label: "Host IP"
      type: "string"
      required: true
      default: "192.168.1.0"
    - variable: "user_id"
      description: "The id your user has on the host machine"
      label: "Your system user ID"
      type: "int"
      required: true
      default: "1000"
    - variable: "user_name"
      description: "The name your user has on the host machine"
      label: "Your system user name"
      type: "string"
      required: true
      default: "developer"
    - variable: "virtual_host"
      description: "The virtual host name you want this project to be accessible at"
      label: "Virtual host name"
      type: "string"
      required: true
      default: "yourprojectname.devbox-yourname.intra"
    - variable: "epp_show_errors"
      description: "Set to true if you want to see all PHP errors in your browser. False is recommended for production"
      label: "Show PHP errors in browser"
      type: "string"
      required: true
      type: "enum"
      options:
        - false
        - true