version: '2'
.catalog:
  name: "Chameleon Host Services"
  version: "1.3"
  description: "Rancher HAProxy, PHPMyAdmin and MariaDB. Version 1.3 Changelog: Switched MySQL to MariaDB 10.1. Removed loadbalancer config"
services:
  phpmyadmin:
    scale: 1
    start_on_create: true
  mysql:
    scale: 1
    start_on_create: true



